<?php
$categories =["Доски и лыжи", "Крепления", "Ботинки", "Одежда", "Инструменты", "Разное"];
$ads = [
  ["title" => "2014 Rossignol District Snowboard",
    "project" => "Доски и лыжи",
    "price" => 10999,
    "url" => "img/lot-1.jpg",
    "exp_date" => "2022-10-30"],
  ["title" => "DC Ply Mens 2016/2017 Snowboard",
    "project" => "Доски и лыжи",
    "price" => 159999,
    "url" => "img/lot-2.jpg",
    "exp_date" => "2022-10-23"],
  ["title" => "Крепления Union Contact Pro 2015 года размер L/XL",
    "project" => "Крепления",
    "price" => 8000,
    "url" => "img/lot-3.jpg",
    "exp_date" => "2022-10-25"],
  ["title" => "Ботинки для сноуборда DC Mutiny Charocal",
    "project" => "Ботинки",
    "price" => 10999,
    "url" => "img/lot-4.jpg",
    "exp_date" => "2022-10-26"],
  ["title" => "Куртка для сноуборда DC Mutiny Charocal",
    "project" => "Одежда",
    "price" => 7500,
    "url" => "img/lot-5.jpg",
    "exp_date" => "2022-10-27"],
  ["title" => "Маска Oakley Canopy",
    "project" => "Разное",
    "price" => 5400,
    "url" => "img/lot-6.jpg",
    "exp_date" => "2022-10-28"],
];
?>
